import fetch from 'node-fetch';

import { validateIsString } from '@pie-dao/utils';

import run from './utils/run';

const repo = process.env.REPO;
const token = process.env.TOKEN;

validateIsString(repo, {
  message: 'Please set environment variable REPO. Ex: REPO="pie-dao/meta" yarn branchProtection"',
});

validateIsString(token, {
  message: 'Please set environment variable TOKEN. Ex: TOKEN="<token>" yarn branchProtection"',
});

const main = async () => {
  const branch = `github-templates-${Date.now()}`;
  const commands = [
    'mkdir -p tmp',
    'cd tmp',
    `git clone git@github.com:${repo} repo`,
    'cd repo',
    `git checkout -b ${branch}`,
    'mkdir -p .github',
    'cp -rfv ../../github/templates/* .github',
    'git add .',
    'git commit -m "update Github templates"',
    `git push -u origin ${branch}`,
    'cd ../',
    'rm -rf repo',
  ];

  await run(commands);

  const url = `https://api.github.com/repos/${repo}/pulls`;
  const headers = { Authorization: `token ${token}` };
  const method = 'POST';
  const body = JSON.stringify({
    title: 'New Github templates',
    head: branch,
    base: 'development',
    body: 'Updates the Github templates. PR generated by pie-dao/meta repo.',
  });

  const response = await fetch(url, { body, headers, method });
  console.log(url, await response.json());
};

main();
