import { terminal } from 'terminal-kit';
import { validateIsString } from '@pie-dao/utils';

import checkoutBranch from './commands/checkoutBranch';
import cloneRepo from './commands/cloneRepo';
import commit from './commands/commit';
import copyES6Linting from './commands/copyES6Linting';
import copyReactLinting from './commands/copyReactLinting';
import deleteRepo from './commands/deleteRepo';
import Github from './adapters/Github';
import pushBranch from './commands/pushBranch';

const repo = process.env.REPO;
const token = process.env.TOKEN;

validateIsString(repo, {
  message: 'Please set environment variable REPO. Ex: REPO="pie-dao/meta" yarn branchProtection"',
});

validateIsString(token, {
  message: 'Please set environment variable TOKEN. Ex: TOKEN="<token>" yarn branchProtection"',
});

const es6Linting = async () => {
  const branch = `feature/linting-es6-${Date.now()}`;

  await cloneRepo(repo);
  await checkoutBranch(branch);
  await copyES6Linting();
  await commit('add linting configuration');
  await pushBranch(branch);
  await deleteRepo();

  return branch;
};

const reactLinting = async () => {
  const branch = `feature/linting-react-${Date.now()}`;

  await cloneRepo(repo);
  await checkoutBranch(branch);
  await copyReactLinting();
  await commit('add linting configuration');
  await pushBranch(branch);
  await deleteRepo();

  return branch;
};

const main = async () => {
  try {
    terminal.bold(`What type of project is ${repo}?`);

    const { selectedIndex, selectedText } = await new Promise((resolve) => {
      terminal.singleColumnMenu([
        'ES6 Library',
        'React Component',
      ], {}, (err, response) => {
        if (err) {
          console.log(err);
          process.exit(1);
        }

        resolve(response);
      });
    });

    let branch;

    if (selectedIndex === 0) {
      branch = await es6Linting();
    }

    if (selectedIndex === 1) {
      branch = await reactLinting();
    }

    const bodyMessage = `Creates ${selectedText.toLowerCase()} eslint setup. PR generated by `
      + 'pie-dao/meta repo.';
    const github = new Github(repo, token);

    console.log(await github.createPullRequest({
      bodyMessage,
      branch,
      title: 'eslint setup',
    }));
  } catch (err) {
    console.log(err);
  }

  process.exit(0);
};

main();
